# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    body_converter:
        enabled: true

    routing_loader:
        include_format: false
        default_format: json
    body_listener: true
    view:
        view_response_listener:  true
        formats:
          json: true
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    exception:
        enabled: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: 'json', priorities: [ 'json','txt' ] }

sensio_framework_extra:
    view: { annotations: true }