#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

rapports:
    type: rest
    resource: App\Controller\RapportController
    prefix: /api